version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: bloodpointbd
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://admin:admin@db:5432/bloodpointbd
      PORT: 8000

volumes:
  postgres_data:
