databases:
  - name: bloodpointbd
    plan: free
    databaseName: bloodpointbd
    user: bloodpointbd

services:
  - type: web
    plan: free
    name: bloodpoint-core
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn bloodpoint_project.asgi:application -k uvicorn.workers.UvicornWorker' 
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bloodpointbd
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: FLASK_APP
        value: "superset.app:create_app()"
      - key: SUPERSET_ENV
        value: production
      - key: SUPERSET_CONFIG_PATH
        value: /opt/render/project/src/config/superset_config.py