databases:
  - name: bloodpointbd
    plan: free
    databaseName: bloodpointbd
    user: bloodpointbd

services:
  - type: web
    plan: free
    name: bloodpoint-core
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn bloodpoint_project.asgi:application -k uvicorn.workers.UvicornWorker' 
    envVars:
      - key: postgresql://admin:MyRta8PfOdy6I11iQ0YBR01CyiGatqzA@dpg-d0gmc82dbo4c73bhc5jg-a/bloodpointbd
        fromDatabase:
          name: bloodpointdb
          property: connectionString
      - key: Okiqzq/LVgWIDvxZ5nCU4bzNxA4Hyi37VD0dIQUeeB8qjaTv39XfJw1v
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4