# Generated by Django 5.2 on 2025-04-11 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloodpoint', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admin',
            new_name='adminbp',
        ),
    ]
