# Generated by Django 5.2 on 2025-04-12 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adminbp',
            fields=[
                ('id_admin', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('contrasena', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='centro_donacion',
            fields=[
                ('id_centro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_centro', models.CharField()),
                ('direccion_centro', models.CharField()),
                ('comuna', models.CharField()),
                ('telefono', models.CharField()),
                ('fecha_creacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='donante',
            fields=[
                ('id_donante', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(unique=True)),
                ('nombre_completo', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('contrasena', models.CharField()),
                ('direccion', models.CharField()),
                ('comuna', models.CharField()),
                ('fono', models.CharField()),
                ('fecha_nacimiento', models.DateField()),
                ('nacionalidad', models.CharField()),
                ('tipo_sangre', models.CharField()),
                ('dispo_dia_donacion', models.DateField()),
                ('nuevo_donante', models.BooleanField()),
                ('noti_emergencia', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='representante_org',
            fields=[
                ('id_representante', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField()),
                ('nombre', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('contrasena', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='campana',
            fields=[
                ('id_campana', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_campana', models.DateField()),
                ('apertura', models.TimeField()),
                ('cierre', models.TimeField()),
                ('meta', models.CharField()),
                ('id_centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodpoint_app.centro_donacion')),
            ],
        ),
        migrations.CreateModel(
            name='donacion',
            fields=[
                ('id_donacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_donacion', models.DateField()),
                ('cantidad_donacion', models.IntegerField()),
                ('centro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodpoint_app.centro_donacion')),
                ('id_donante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodpoint_app.donante')),
            ],
        ),
        migrations.CreateModel(
            name='logro',
            fields=[
                ('id_logro', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_logro', models.CharField()),
                ('fecha_logro', models.DateField()),
                ('id_donante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodpoint_app.donante')),
            ],
        ),
        migrations.AddField(
            model_name='centro_donacion',
            name='id_representante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodpoint_app.representante_org'),
        ),
        migrations.CreateModel(
            name='solicitud_campana_repo',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_sangre_sol', models.CharField()),
                ('fecha_solicitud', models.DateField()),
                ('cantidad_personas', models.IntegerField()),
                ('descripcion_solicitud', models.CharField()),
                ('direccion_solicitud', models.CharField()),
                ('comuna_solicitud', models.CharField()),
                ('id_donante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodpoint_app.donante')),
            ],
        ),
    ]
