# Generated by Django 5.2 on 2025-04-19 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodpoint_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='test_field',
        ),
        migrations.AddField(
            model_name='customuser',
            name='rut',
            field=models.CharField(default='sin-rut', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='donante',
            name='rut',
            field=models.CharField(unique=True),
        ),
    ]
