# Generated by Django 5.2 on 2025-04-12 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodpoint_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donante',
            name='noti_emergencia',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='donante',
            name='nuevo_donante',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='donante',
            name='tipo_sangre',
            field=models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3),
        ),
    ]
