# Generated by Django 5.2 on 2025-05-17 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodpoint_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='representante_org',
            name='verificado',
            field=models.BooleanField(default=False),
        ),
    ]
