# Generated by Django 5.2 on 2025-05-22 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodpoint_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud_campana_repo',
            name='direccion_solicitud',
        ),
        migrations.RemoveField(
            model_name='solicitud_campana_repo',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='solicitud_campana_repo',
            name='longitud',
        ),
        migrations.AddField(
            model_name='campana',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('desarrollandose', 'Desarrollándose'), ('cancelado', 'Cancelado'), ('completo', 'Completo')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='campana',
            name='fecha_termino',
            field=models.DateField(default='2002-02-02'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campana',
            name='id_solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bloodpoint_app.solicitud_campana_repo'),
        ),
        migrations.AddField(
            model_name='campana',
            name='validada',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='centro_donacion',
            name='horario_apertura',
            field=models.TimeField(default='09:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='centro_donacion',
            name='horario_cierre',
            field=models.TimeField(default='09:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donacion',
            name='campana_relacionada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bloodpoint_app.campana'),
        ),
        migrations.AddField(
            model_name='donacion',
            name='solicitud_relacionada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bloodpoint_app.solicitud_campana_repo'),
        ),
        migrations.AddField(
            model_name='donacion',
            name='tipo_donacion',
            field=models.CharField(choices=[('punto', 'Punto de Donación'), ('campana', 'Campaña'), ('solicitud', 'Solicitud de Campaña')], default='campana', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitud_campana_repo',
            name='campana_asociada',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bloodpoint_app.campana'),
        ),
        migrations.AddField(
            model_name='solicitud_campana_repo',
            name='centro_donacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bloodpoint_app.centro_donacion'),
        ),
        migrations.AddField(
            model_name='solicitud_campana_repo',
            name='ciudad_solicitud',
            field=models.CharField(default='iquique'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitud_campana_repo',
            name='desactivado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bloodpoint_app.representante_org'),
        ),
        migrations.AddField(
            model_name='solicitud_campana_repo',
            name='fecha_termino',
            field=models.DateField(default='2002-02-02'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitud_campana_repo',
            name='region_solicitud',
            field=models.CharField(default='Tarapaca'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campana',
            name='id_representante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bloodpoint_app.representante_org'),
        ),
    ]
