# Generated by Django 5.2 on 2025-05-22 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodpoint_app', '0002_remove_solicitud_campana_repo_direccion_solicitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminbp',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='adminbp',
            name='contrasena',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='adminbp',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='adminbp',
            name='rol',
            field=models.CharField(max_length=50),
        ),
    ]
