# Generated by Django 5.2 on 2025-04-18 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodpoint_app', '0002_alter_donante_noti_emergencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campana',
            name='id_representante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bloodpoint_app.representante_org'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campana',
            name='latitud',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campana',
            name='longitud',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitud_campana_repo',
            name='latitud',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitud_campana_repo',
            name='longitud',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donante',
            name='dispo_dia_donacion',
            field=models.CharField(),
        ),
    ]
