# Generated by Django 5.2 on 2025-04-29 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodpoint_app', '0002_adminbp_created_at_campana_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='representante_org',
            name='contrasena',
        ),
        migrations.RemoveField(
            model_name='representante_org',
            name='email',
        ),
        migrations.AddField(
            model_name='donante',
            name='sexo',
            field=models.CharField(default='M', max_length=1),
            preserve_default=False,
        ),
    ]
