# Generated by Django 5.2 on 2025-04-29 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodpoint_app', '0003_remove_representante_org_contrasena_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='representante_org',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
