# Generated by Django 5.2 on 2025-04-19 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodpoint_app', '0003_alter_customuser_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rut',
            field=models.CharField(default='rut-default', unique=True),
            preserve_default=False,
        ),
    ]
