# Generated by Django 5.2 on 2025-05-23 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloodpoint_app', '0004_alter_customuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminbp',
            name='rol',
        ),
    ]
