# Generated by Django 5.2 on 2025-05-23 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloodpoint_app', '0005_remove_adminbp_rol'),
    ]

    operations = [
        migrations.RunSQL(
            sql='ALTER TABLE bloodpoint_app_adminbp DROP COLUMN IF EXISTS rol;',
            reverse_sql='ALTER TABLE bloodpoint_app_adminbp ADD COLUMN rol varchar(255);'
        )
    ]
